---
abstract: 'Make tests wait for manual testing purposes.'
author:
  - 'Ben Hare <ben@benhare.com>'
build_requires:
  ExtUtils::MakeMaker: 6.76
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Wait
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 0
version: 0.04
